### ISSUE TITLE
Enable web push notifications 

### ISSUE THREAD

**Issue by gauthamzz** [nybles/nybles.github.io#4]

**Comment by Anupam-dagar** [comment]
Should individual API for different browser be used or a third party service like One Signal can also be used?

**Comment by gauthamzz** [comment]
you can use anything :)

**Comment by gauthamzz** [comment]
https://pushcrew.com this is one of them

**Comment by magician03** [comment]
@Anupam-dagar , I request you not to proceed with this issue, there are other important issues to be solved right now.

**Comment by gauthamzz** [comment]
@Anupam-dagar update ?

**Comment by aswinzz** [comment]
Done
