### ISSUE TITLE
Enable global search

### ISSUE THREAD

**Issue by magician03** [nybles/nybles.github.io#44]

**Comment by pradeepgangwar** [comment]
I am working on it .......... work has been completed ........... i will be pushing my changes to my fork in some time.

**Comment by pradeepgangwar** [comment]
got to :-  https://pradeepgangwar.github.io/nybles.github.io/  
Plaese note that on entering search item result will not display ........ beacuse of URL mismatch ......... but it will work all fine on main page. 

for demo search result display :- https://pradeepgangwar.github.io/nybles.github.io/search.html?query=quantum

**Comment by mubaris** [comment]
Send the PR

**Comment by gauthamzz** [comment]
please make the changes in #56 @pradeepgangwar

**Comment by gauthamzz** [comment]
solved in #56 #57
