### ISSUE TITLE
Enable Editor in menu

### ISSUE THREAD

**Issue by gauthamzz** [nybles/nybles.github.io#54]
You can perform this,but the pr will be merged only when the editor is in stable condition

Should link to editor in nybles organisation

**Comment by aswinzz** [comment]
I will work on this

**Comment by himanshub16** [comment]
I would advise to either make sure your PR is bit modular in nature (some script in _includes folder) so that it doesn't cause merge conflict if left for some time.
Otherwise, refrain from making PR.

**Comment by aswinzz** [comment]
sure sir

**Comment by gauthamzz** [comment]
dude dont call anyone sir on github -_- @aswinzz

**Comment by aswinzz** [comment]
okay!
