### ISSUE TITLE
Improve UI in circular area

### ISSUE THREAD

**Issue by anweshknayak** [nybles/nybles.github.io#61]
Beautify the CSS or do something to make the UI better of the circle below

![screenshot from 2017-03-20 17 59 22](https://cloud.githubusercontent.com/assets/8139783/24099923/b8549444-0d97-11e7-98db-39181de40dea.png)

**Comment by pradeepgangwar** [comment]
Any one making these changes in should also make changes in **search.js** else the same changes will not reflect in search result. I can help if anyone has problem editing **search.js** code, like where it is to be done.

**Comment by pradeepgangwar** [comment]
@Anupam-dagar @aswinzz Try this

**Comment by gauthamzz** [comment]
is anyone working on this ?

**Comment by pradeepgangwar** [comment]
Provide reviews for this change...
![pic1](https://cloud.githubusercontent.com/assets/21259802/24120489/c77a3d3c-0dda-11e7-97fc-1b5be1e4c36a.png)

**Comment by anweshknayak** [comment]
@gauthamzz any suggestions ?

**Comment by himanshub16** [comment]
It's good but looks like "like" button. Do you have any other suggestions?

**Comment by pradeepgangwar** [comment]
go to gitter chat for a new design.

**Comment by anweshknayak** [comment]
@pradeepgangwar as @aswinzz said try to match a bit with the background colour. too much contrast is not much good for UI.

**Comment by pradeepgangwar** [comment]
go to :-  http://pradeepgangwar.tech/nybles.github.io/ for latest changes. As said before suggest a icon of ur choice :)

**Comment by gauthamzz** [comment]
LGTM send pr
