### ISSUE TITLE
Proper placeholder for Like and Share button

### ISSUE THREAD

**Issue by anweshknayak** [nybles/nybles.github.io#64]
Needs to be placed somewhere else in the page.
and UI enhancement for both buttons.

**Comment by aswinzz** [comment]
![screenshot from 2017-03-22 18-42-13](https://cloud.githubusercontent.com/assets/25057819/24199389/5a0580a8-0f2f-11e7-89b7-575df6d99a12.png)
Is this enough?

**Comment by anweshknayak** [comment]
Looks good to me. @himanshub16 @gauthamzz suggestions ?

**Comment by himanshub16** [comment]
![image](https://cloud.githubusercontent.com/assets/14041572/24203954/1415c98c-0f3d-11e7-84b1-69a5b67abac2.png)

Good... but some issues with responsiveness.

**Comment by aswinzz** [comment]
i corrected it like when it is in desktop view it will as i changed and when it is in mobile view it will be the old one itself.
is that fine?

**Comment by anweshknayak** [comment]
@himanshub16 Let's put the responsiveness part for version 2.0 . We need to quickly fix the smaller problems now. 

@aswinzz Nice work. Please send a PR.

**Comment by gauthamzz** [comment]
i checked this out,it looks really weird in mobile view, the current version seems better
https://aswinzz.github.io/nybles.github.io/
plus its making the whole page white in color,getting rid of any distinction between header other sections

**Comment by anweshknayak** [comment]
@gauthamzz lets make another PR for that. the white colour. under UI improvement for that section.

**Comment by aswinzz** [comment]
im making the PR

**Comment by anweshknayak** [comment]
@aswinzz don't remove the colour of whole page in your PR. as in make it white. @gauthamzz I missed your comment.

**Comment by aswinzz** [comment]
ok ill fix it
