### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by gauthamzz** [nybles/nybles.github.io#7]

**Comment by aswinzz** [comment]
I will work on this

**Comment by gauthamzz** [comment]
Solved #30

**Comment by himanshub16** [comment]
https://github.com/nybles/nybles.github.io/pull/30#pullrequestreview-26730030

**Comment by gauthamzz** [comment]
https://github.com/aswinzz/nybles.github.io/blob/9fc45f19139164dcf0bbebc1ecc1f234e7b80c81/static/css/loader.css#L11 needs to be variable

**Comment by gauthamzz** [comment]
solved in #30 #34 , thanks @aswinzz
