### ISSUE TITLE
Add a rating system to posts.

### ISSUE THREAD

**Issue by Anupam-dagar** [nybles/nybles.github.io#8]
Something similar to likes on facebook or upvotes on quora should be added to each post.It can be a star also.

**Comment by gauthamzz** [comment]
We have it near comments as of now.

**Comment by Anupam-dagar** [comment]
is it recommend button?

**Comment by gauthamzz** [comment]
yeah

**Comment by gauthamzz** [comment]
This issue is open ,you just needs to show the amount of recomends the post gets from disqus.

**Comment by CodHeK** [comment]
I would like to work on this :p

**Comment by gauthamzz** [comment]
sure :+1:
