### ISSUE TITLE
Improve experience with the editor

### ISSUE THREAD

**Issue by himanshub16** [nybles/nybles.github.io#81]
The editor as of now works, but has some issues.
* The text sometimes doesn't appear.
* The size of input textarea varies rapidly, which is irritating.

Here is [original fork](https://github.com/jbt/markdown-editor), which has been modified to suit our requirements. One can refer to the original codebase to fix experience.

**Comment by himanshub16** [comment]
I've created the backend part. You can refer to the readme here > https://github.com/nybles/nybles.github.io/tree/master/cgi-bin
Just work on some simple interface, so that these articles can be viewed.
Don't put too much effort and make it complicated.

**Comment by gauthamzz** [comment]
how would you suggest we do this ? 

I think a simple page named submissions would do

**Comment by himanshub16** [comment]
Fixed in https://github.com/nybles/markdown-editor/commit/e924727de53699f89a22feff7d4dc552c414ae33
